// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaHotel.Persistencia.EFCore.Database.Contexts;

#nullable disable

namespace SistemaHotel.Persistenia.EFCore.Migrations
{
    [DbContext(typeof(SqliteEFCoreContext))]
    [Migration("20241008154218_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SistemaHotel.Modelo.Basicas.QuartoModelo", b =>
                {
                    b.Property<int>("QuartoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponibilidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("QuartoID");

                    b.ToTable("Quartos");
                });

            modelBuilder.Entity("SistemaHotel.Modelo.Basicas.RelatorioModelo", b =>
                {
                    b.Property<int>("RelatorioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Faturamento")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQuartos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalReservas")
                        .HasColumnType("INTEGER");

                    b.HasKey("RelatorioID");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("SistemaHotel.Modelo.Basicas.ReservaModelo", b =>
                {
                    b.Property<int>("ReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCheckOut")
                        .HasColumnType("TEXT");

                    b.HasKey("ReservaID");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("SistemaHotel.Modelo.Basicas.UsuarioModelo", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("RG")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
